language: generic

sudo: required

services:
  - docker

env:
  - DIST=fedora30
  - DIST=fedoradev
  - DIST=opensuselp15
  - DIST=opensusetw

before_install:
  - docker build -t $DIST -f test/Dockerfile-$DIST .

script:
  - docker run -v $(pwd):/usr/src/rpmlint/ $DIST python3 setup.py test
  - docker run -v $(pwd):/usr/src/rpmlint/ $DIST flake8
