language: generic

sudo: required

services:
  - docker

env:
  - DIST=fedora29
  - DIST=fedoradev
  - DIST=opensuselp15
  - DIST=opensusetw

before_install:
  - docker build -t $DIST -f test/Dockerfile-$DIST .

script:
  - docker run -e PYTHONPATH='.' $DIST python3 setup.py test
  - docker run $DIST flake8
