language: generic

sudo: required

services:
  - docker

env:
  - DIST=centos7 PYTHON=python
  - DIST=fedora28 PYTHON=python3
  - DIST=fedoradev PYTHON=python3

before_install:
  - docker build -t $DIST -f test/Dockerfile-$DIST .

script:
  - docker run $DIST $PYTHON setup.py test
