language: generic

sudo: required

services:
  - docker

env:
  - DIST=centos6 PYTHON=python PYTEST=py.test FLAKE8=true
  #- DIST=ubuntu14 PYTHON=python PYTEST=py.test FLAKE8=true
  #- DIST=fedora24 PYTHON=python3 PYTEST=py.test-3 FLAKE8=python3-flake8
  - DIST=fedoradev PYTHON=python3 PYTEST=py.test FLAKE8=flake8

before_install:
  - docker build -t $DIST -f test/Dockerfile-$DIST .

script:
  - docker run -e PYTHON=$PYTHON -e PYTEST=$PYTEST -e FLAKE8=$FLAKE8 $DIST test/docker-script.sh
