score-file-must-not-be-conffile="""
A file in /var/lib/games/ is a configuration file. Store your conf
files in /etc instead.
"""
non-etc-or-var-file-marked-as-conffile="""
A file not in /etc or /var is marked as being a configuration file.
Please put your configuration files in /etc or /var.
"""
conffile-without-noreplace-flag="""
A configuration file is stored in your package without the noreplace flag.
A way to resolve this is to put the following in your SPEC file:

%config(noreplace) /etc/your_config_file_here
"""
